### ISSUE TITLE
daemon is not compatible with AWS provider: runtime error: invalid memory address

### ISSUE THREAD

**Issue by sunya-ch** [foundation-model-stack/multi-nic-cni#56]
- [ ] checked https://foundation-model-stack.github.io/multi-nic-cni/user_guide/troubleshooting/.
- [ ] titled with the bug issue (if applicable).
- [ ] provided corresponding information regarding the troubleshooting guidelines (CR list/detail, multi-nic cni controller and/or daemon status/log).

**Describe the bug**

Daemon cannot create routes on AWS machine. 

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.: 
 - log of failed multi-nicd pod: 

 ```bash
2023/01/19 07:40:39 Delete L3 config multinic-ipvlanl3 (false): Failed to get tableID
2023/01/19 07:40:39 force delete multinic-ipvlanl3 (-1)
2023/01/19 07:40:39 delete rule ip rule -1: from <nil> table 100:no such file or directory
2023/01/19 07:40:39 add rule ip rule -1: from 192.168.0.0/16 table 100:<nil>
2023/01/19 07:40:39 Apply L3 config 100; (true)
2023/01/19 07:40:39 cannnot get name: no net or virtio folder from /sys/bus/pci/devices/0000:00:07.0
2023/01/19 07:40:39 cannot list address on ens5: <nil>
2023/01/19 07:40:39 Acknowledge greeting from 10.0.147.22
2023/01/19 07:40:39 Acknowledge greeting from 10.0.147.22
2023/01/19 07:40:39 delete 0 of 0 routes from table 100
2023/01/19 07:40:39 delete rule ip rule -1: from <nil> table 100:<nil>
2023/01/19 07:40:39 Delete L3 config multinic-ipvlanl3 (true):
2023/01/19 07:40:39 force delete multinic-ipvlanl3 (100)
2023/01/19 07:40:39 delete rule ip rule -1: from <nil> table 100:no such file or directory
2023/01/19 07:40:39 add rule ip rule -1: from 192.168.0.0/16 table 100:<nil>
2023/01/19 07:40:39 http: panic serving 10.0.135.25:54984: runtime error: invalid memory address or nil pointer dereference
goroutine 47 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x12f0860, 0x20761e0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
net.networkNumberAndMask(0x0)
	/usr/local/go/src/net/ip.go:498
net.(*IPNet).String(0xc0005dc180)
	/usr/local/go/src/net/ip.go:548 +0x2b
github.com/foundation-model-stack/multi-nic-cni/daemon/router.isRouteExist({0x3, 0x0, 0x0, 0xc000504f30, {0x0, 0x0, 0x0}, {0xc000482310, 0x10, 0x10}, ...}, ...)
	/usr/local/app/src/router/router.go:171 +0x109
github.com/foundation-model-stack/multi-nic-cni/daemon/router.ApplyL3Config(0x7f7b6eeba108)
	/usr/local/app/src/router/router.go:44 +0x307
main.ApplyL3Config({0x163cb48, 0xc000f40000}, 0xc000504360)
	/usr/local/app/src/main.go:151 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc000f38300, {0x163cb48, 0xc000f40000}, 0xc000a0d9f8)
	/usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001c2180, {0x163cb48, 0xc000f40000}, 0xc000f38200)
	/root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0x16314f0}, {0x163cb48, 0xc000f40000}, 0xc000f38200)
	/usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0005e40a0, {0x16406f0, 0xc000504480})
	/usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3033 +0x4e8
```

- debug node
```bash
sh-4.4# ip rule
0:	from all lookup local
29:	from 192.168.0.0/16 lookup multinic-ipvlanl3
30:	from all fwmark 0x1745ec lookup 7
32766:	from all lookup main
32767:	from all lookup default
sh-4.4# ip route show table multinic-ipvlanl3
Error: ipv4: FIB table does not exist.
Dump terminated
```

**Environment (please complete the following information):**
 - platform: OpenShift on AWS
 - node profile:
 - operator version : 
 - cluster scale (number of nodes, pods, interfaces):2 worker nodes 1 secondary interfaces

**Additional context**

Signed-off-by: Sunyanan Choochotkaew [sunyanan.choochotkaew1@ibm.com](mailto:sunyanan.choochotkaew1@ibm.com)

**Comment by sunya-ch** [comment]
Should be fixed by https://github.com/foundation-model-stack/multi-nic-cni/pull/58.
